version: '3'

networks:
  bridged-network:
    driver: bridge

volumes:
  jenkins-home:
  prometheus-data:

services:

  jenkins:
    image: jenkins-docker:1.0.0
    user: "root:root"
    networks:
      - bridged-network
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - jenkins-home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:v2.4.2
    networks:
    - bridged-network
    ports:
    - 9090:9090
    volumes:
    - prometheus-data:/prometheus
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  awande:
    image: awande:v0.6.0
    networks:
    - bridged-network
    ports:
    - 8090:8090
    - 8091:8091